apiVersion: v1
appVersion: "1.0"
description: 'A helm chart used to lockdown all ingress and egress for a namespace '
home: https://kubernetes.io/docs/concepts/services-networking/network-policies/
name: lockdown
version: 0.1.0
