---
pod:
  mandatory_access_control:
    type: apparmor
    postgresql:
      postgresql: runtime/default
      set-volume-perms: runtime/default
      init: runtime/default
    prometheus-postgresql-exporter:
      postgresql-exporter: runtime/default
      init: runtime/default
    prometheus-postgresql-exporter-create-user:
      prometheus-postgresql-exporter-create-user: runtime/default
      init: runtime/default
    postgresql-backup:
      init: runtime/default
      backup-perms: runtime/default
      postgresql-backup: runtime/default
manifests:
  cron_job_postgresql_backup: true
...
