---
pod:
  mandatory_access_control:
    type: apparmor
    rabbitmq-cluster-wait:
      init: runtime/default
      rabbitmq-cookie: runtime/default
      rabbitmq-rabbitmq-cluster-wait: runtime/default
    rabbitmq:
      init: runtime/default
      rabbitmq-password: runtime/default
      rabbitmq-cookie: runtime/default
      rabbitmq-perms: runtime/default
      rabbitmq: runtime/default
    prometheus-rabbitmq-exporter:
      init: runtime/default
      rabbitmq-exporter: runtime/default
    rabbitmq-rabbitmq-test:
      rabbitmq-rabbitmq-test: runtime/default
      init: runtime/default

monitoring:
  prometheus:
    enabled: true
...
