---
pod:
  mandatory_access_control:
    type: apparmor
    grafana:
      grafana: runtime/default
      init: runtime/default
    grafana-db-init-session:
      grafana-db-init-session: runtime/default
      init: runtime/default
    grafana-db-init:
      grafana-db-init: runtime/default
      init: runtime/default
    grafana-db-session-sync:
      grafana-db-session-sync: runtime/default
      init: runtime/default
    grafana-set-admin-user:
      grafana-set-admin-password: runtime/default
      init: runtime/default
    grafana-test:
      init: runtime/default
      grafana-selenium-tests: runtime/default
...
