---
conf:
  kibana:
    elasticsearch:
      ssl:
        certificateAuthorities: ["/etc/elasticsearch/certs/ca.crt"]
        verificationMode: certificate
endpoints:
  elasticsearch:
    scheme:
      default: "https"
    port:
      http:
        default: 443
  kibana:
    host_fqdn_override:
      default:
        tls:
          issuerRef:
            name: ca-issuer
            kind: ClusterIssue
manifests:
  certificates: true
...
