---
pod:
  mandatory_access_control:
    type: apparmor
    ceph-mon:
      ceph-init-dirs: runtime/default
      ceph-mon: runtime/default
      ceph-log-ownership: runtime/default
    ceph-mon-check:
      ceph-mon: runtime/default
      init: runtime/default
    ceph-bootstrap:
      ceph-bootstrap: runtime/default
      init: runtime/default
    ceph-storage-keys-generator:
      ceph-storage-keys-generator: runtime/default
      init: runtime/default
    ceph-mon-keyring-generator:
      ceph-mon-keyring-generator: runtime/default
      init: runtime/default
    ceph-mgr-keyring-generator:
      init: runtime/default
      ceph-mgr-keyring-generator: runtime/default
    ceph-mds-keyring-generator:
      init: runtime/default
      ceph-mds-keyring-generator: runtime/default
    ceph-osd-keyring-generator:
      ceph-osd-keyring-generator: runtime/default
      init: runtime/default
bootstrap:
  enabled: true
manifests:
  job_bootstrap: true
...
