---
pod:
  env:
    client: null
    data: null
    master: null
  mandatory_access_control:
    type: apparmor
    elasticsearch-master:
      elasticsearch-master: runtime/default
      init: runtime/default
      memory-map-increase: runtime/default
    elasticsearch-data:
      elasticsearch-data: runtime/default
      init: runtime/default
      memory-map-increase: runtime/default
    elasticsearch-client:
      elasticsearch-client: runtime/default
      init: runtime/default
      memory-map-increase: runtime/default
      apache-proxy: runtime/default
    prometheus-elasticsearch-exporter:
      elasticsearch-exporter: runtime/default
      init: runtime/default
    elasticsearch-test:
      init: runtime/default
      elasticsearch-helm-tests: runtime/default
    create-elasticsearch-templates:
      create-elasticsearch-templates: runtime/default
      init: runtime/default
    elasticsearch-verify-repositories:
      elasticsearch-verify-repositories: runtime/default
      init: runtime/default
...
