---
manifests:
  network_policy: true
network_policy:
  postgresql:
    egress:
      - to:
        - ipBlock:
            cidr: %%%REPLACE_API_ADDR%%%/32
        ports:
          - protocol: TCP
            port: %%%REPLACE_API_PORT%%%
...
