# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for NFS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
pod:
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
      weight:
        default: 10
  replicas:
    # only 1 replica currently supported
    server: 1
  resources:
    enabled: false
    server:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

images:
  tags:
    nfs_provisioner: quay.io/kubernetes_incubator/nfs-provisioner:v2.2.1-k8s1.12
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    image_repo_sync: docker.io/library/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

storage:
  type: hostPath
  hostPath:
    path: /var/lib/openstack-helm/nfs
  persistentVolumeClaim:
    access_mode: ReadWriteOnce
    class_name: general
    # NOTE(portdirect): Unless explicity set the PV name will be populated to
    # match "{{ .Release.Name }}".
    name: null
    size: 10Gi

labels:
  nfs:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

storageclass:
  # NOTE(portdirect): Unless explicity set the provisioner name will be generated
  # with the format "nfs/{{ .Release.Name }}"
  provisioner: null
  # NOTE(portdirect): Unless explicity set the PV name will be populated to
  # match "{{ .Release.Name }}".
  name: null

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - nfs-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry
    nfs:
      services: null

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  nfs:
    hosts:
      default: nfs-provisioner
    host_fqdn_override:
      default: null
    path: null
    scheme: null
    port:
      nfs:
        default: null

manifests:
  configmap_bin: true
  deployment: true
  job_image_repo_sync: true
  service: true
  storage_class: true
  volume_claim: true
...
