---
pod:
  mandatory_access_control:
    type: apparmor
    mariadb-ingress-error-pages:
      init: runtime/default
      ingress-error-pages: runtime/default
    mariadb-ingress:
      init: runtime/default
      ingress: runtime/default
    mariadb-server:
      init: runtime/default
      mariadb-perms: runtime/default
      mariadb: runtime/default
    mariadb-backup:
      init: runtime/default
      mariadb-backup: runtime/default
    mariadb-test:
      init: runtime/default
      mariadb-test: runtime/default
    prometheus-mysql-exporter:
      init: runtime/default
      mysql-exporter: runtime/default
    create-sql-user:
      init: runtime/default
      exporter-create-sql-user: runtime/default

monitoring:
  prometheus:
    enabled: true

manifests:
  cron_job_mariadb_backup: true
...
