# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for powerdns.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

---
images:
  tags:
    powerdns: docker.io/psitrax/powerdns:4.1.10
    db_init: docker.io/openstackhelm/heat:queens-ubuntu_xenial
    db_sync: docker.io/psitrax/powerdns:4.1.10
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    image_repo_sync: docker.io/library/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

pod:
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
      weight:
        default: 10
  replicas:
    server: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
  resources:
    enabled: false
    server:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    jobs:
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      tests:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

labels:
  powerdns:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  test:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - powerdns-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry
    powerdns:
      jobs:
        - powerdns-db-init
        - powerdns-db-sync
      services:
        - endpoint: internal
          service: oslo_db
    db_init:
      services:
        - endpoint: internal
          service: oslo_db
    db_sync:
      jobs:
        - powerdns-db-init
      services:
        - service: oslo_db
          endpoint: internal

network:
  node_port_enabled: true
  external_policy_local: true

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  powerdns:
    auth:
      service:
        token: chiave_segreta
    hosts:
      default: powerdns
    host_fqdn_override:
      default: null
    port:
      powerdns_api:
        default: 8081
      powerdns_tcp:
        default: 53
      powerdns:
        default: 53
        protocol: UDP
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      powerdns:
        username: powerdns
        password: password
    hosts:
      default: mariadb
    host_fqdn_override:
      default: null
    path: /powerdns
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306

secrets:
  oslo_db:
    admin: powerdns-db-admin
    powerdns: powerdns-db-user

conf:
  powerdns:
    slave: true
    dnsupdate: true
    api: true
    cache_ttl: 0
    query_cache_ttl: 0
    negquery_cache_ttl: 0
    out_of_zone_additional_processing: no
    webserver: true
    webserver_address: 0.0.0.0
    webserver_allow_from: 0.0.0.0/0
    gmysql_dbname: powerdns
    gmysql_dnssec: yes
  mysql:
    client:
      database: powerdns

manifests:
  configmap_bin: true
  configmap_etc: true
  deployment: true
  job_db_init: true
  job_db_sync: true
  secret_db: true
  service_dns: true
  service_api: false
...
