---
pod:
  security_context:
    server:
      container:
        perms:
          readOnlyRootFilesystem: false
        mariadb:
          runAsUser: 0
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
endpoints:
  oslo_db:
    host_fqdn_override:
      default:
        tls:
          secretName: mariadb-tls-direct
          issuerRef:
            name: ca-issuer
            kind: ClusterIssuer
manifests:
  certificates: true
...
