---
pod:
  mandatory_access_control:
    type: apparmor
    ceph-rgw:
      init: runtime/default
      ceph-rgw: runtime/default
      ceph-init-dirs: runtime/default
      ceph-rgw-init: runtime/default
    ceph-rgw-bootstrap:
      ceph-keyring-placement: runtime/default
      init: runtime/default
      ceph-rgw-bootstrap: runtime/default
    ceph-rgw-storage-init:
      ceph-keyring-placement: runtime/default
      init: runtime/default
      ceph-rgw-storage-init: runtime/default
    ceph-rgw-s3-admin:
      ceph-keyring-placement: runtime/default
      init: runtime/default
      create-s3-admin: runtime/default
    ceph-rgw-test:
      ceph-rgw-ks-validation: runtime/default
      ceph-rgw-s3-validation: runtime/default
conf:
  rgw_s3:
    enabled: true
bootstrap:
  enabled: true
manifests:
  job_bootstrap: true
...
