---
manifests:
  network_policy: true
network_policy:
  rgw:
    egress:
      - to:
        - ipBlock:
            cidr: 172.17.0.1/16
      - to:
        ports:
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 443
      - to:
        - ipBlock:
            cidr: %%%REPLACE_API_ADDR%%%/32
        ports:
          - protocol: TCP
            port: %%%REPLACE_API_PORT%%%
...
