---
endpoints:
  object_store:
    scheme:
      default: https
    host_fqdn_override:
      default:
        tls:
          secretName: ceph-rgw-ks-tls-api
          issuerRef:
            name: ca-issuer
            kind: ClusterIssuer
  ceph_object_store:
    scheme:
      default: https
    host_fqdn_override:
      default:
        tls:
          secretName: ceph-rgw-s3-tls-api
          issuerRef:
            name: ca-issuer
            kind: ClusterIssuer

network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx-cluster"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      external_policy_local: false
      node_port:
        enabled: false
        port: 30004
    public: 192.168.0.0/16
    cluster: 192.168.0.0/16

manifests:
  certificates: true
...
