---
endpoints:
  monitoring:
    scheme:
      default: "https"
    port:
      http:
        default: 443
  elasticsearch:
    scheme:
      default: "https"
    port:
      http:
        default: 443
manifests:
  certificates: true
...
