---
pod:
  mandatory_access_control:
    type: apparmor
    prometheus-openstack-exporter:
      openstack-metrics-exporter: runtime/default
      init: runtime/default
    prometheus-openstack-exporter-ks-user:
      prometheus-openstack-exporter-ks-user: runtime/default
      init: runtime/default
...
