# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for process-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
images:
  tags:
    process_exporter: docker.io/ncabatoff/process-exporter:0.2.11
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    image_repo_sync: docker.io/library/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

labels:
  process_exporter:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

pod:
  security_context:
    metrics:
      pod:
        runAsUser: 65534
      container:
        process_exporter:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
      weight:
        default: 10
  mounts:
    process_exporter:
      process_exporter:
      init_container: null
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        process_exporter:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
    termination_grace_period:
      process_exporter:
        timeout: 30
  resources:
    enabled: false
    process_exporter:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
  tolerations:
    process_exporter:
      enabled: false
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      - key: node-role.kubernetes.io/node
        operator: Exists
dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - process-exporter-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry
    process_exporter:
      services: null

monitoring:
  prometheus:
    enabled: true
    process_exporter:
      scrape: true

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  process_exporter_metrics:
    namespace: null
    hosts:
      default: process-exporter
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      metrics:
        default: 9256

network_policy:
  process_exporter:
    ingress:
      - {}
    egress:
      - {}

manifests:
  configmap_bin: true
  daemonset: true
  job_image_repo_sync: true
  service: true

conf:
  processes: dockerd,kubelet,kube-proxy,bgsagent,bgscollect,bgssd
  children: true
...
