---
pod:
  mandatory_access_control:
    type: apparmor
    nagios:
      nagios: runtime/default
      init: runtime/default
      define-nagios-hosts: runtime/default
      apache-proxy: runtime/default
    nagios-test:
      init: runtime/default
      nagios-helm-tests: runtime/default
...
