---
pod:
  mandatory_access_control:
    type: apparmor
    ceph-checkdns:
      ceph-checkdns: runtime/default
      init: runtime/default
    ceph-mds:
      ceph-mds: runtime/default
      ceph-init-dirs: runtime/default
    ceph-mgr:
      ceph-mgr: runtime/default
      ceph-init-dirs: runtime/default
    ceph-rbd-pool:
      ceph-rbd-pool: runtime/default
      init: runtime/default
    ceph-client-bootstrap:
      ceph-client-bootstrap: runtime/default
      init: runtime/default
    ceph-client-test:
      init: runtime/default
      ceph-cluster-helm-test: runtime/default
bootstrap:
  enabled: true
manifests:
  job_bootstrap: true

...
