---
conf:
  postgresql:
    ssl: 'on'
pod:
  security_context:
    server:
      container:
        perms:
          readOnlyRootFilesystem: false
        postgresql:
          runAsUser: 0
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
endpoints:
  postgresql:
    host_fqdn_override:
      default:
        tls:
          secretName: postgresql-tls-direct
          issuerRef:
            name: ca-issuer
            kind: ClusterIssuer
manifests:
  certificates: true
...
