---
conf:
  persistent_volumes:
    - name: local-persistent-volume-0
      reclaim_policy: Delete
      storage_capacity: "1Gi"
      access_modes: ["ReadWriteOnce"]
      local_path: /srv/local-volume-0
    - name: local-persistent-volume-1
      reclaim_policy: Delete
      storage_capacity: "1Gi"
      access_modes: ["ReadWriteOnce"]
      local_path: /srv/local-volume-1
    - name: local-persistent-volume-2
      reclaim_policy: Delete
      storage_capacity: "1Gi"
      access_modes: ["ReadWriteOnce"]
      local_path: /srv/local-volume-2
    - name: local-persistent-volume-3
      reclaim_policy: Delete
      storage_capacity: "1Gi"
      access_modes: ["ReadWriteOnce"]
      local_path: /srv/local-volume-3
    - name: local-persistent-volume-4
      reclaim_policy: Delete
      storage_capacity: "1Gi"
      access_modes: ["ReadWriteOnce"]
      local_path: /srv/local-volume-4
    - name: local-persistent-volume-5
      reclaim_policy: Delete
      storage_capacity: "1Gi"
      access_modes: ["ReadWriteOnce"]
      local_path: /srv/local-volume-5
manifests:
  storage_class: true
  persistent_volumes: true
...
